version: "3.9"
networks:
  default:
    driver: bridge
services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default
    labels:
    command:
      - --port=2001
